### ISSUE TITLE
Error when run app

### ISSUE THREAD

**Issue by duy-nirvana** [regulaforensics/react-native-face-api#1]
I'm install library successfully, but when i run app, it has an error:
![image](https://user-images.githubusercontent.com/54000074/120100477-29b01880-c16b-11eb-95ce-6d5bf8a695de.png)
![image](https://user-images.githubusercontent.com/54000074/120100484-36347100-c16b-11eb-9a10-56896faca676.png)
I hope you can help me, thanks!

**Comment by PavelMasuk** [comment]
fixed in @regulaforensics/react-native-face-api-beta@0.0.23

**Comment by duy-nirvana** [comment]
thank for your help 💯
