### ISSUE TITLE
Podspecs file is missing

### ISSUE THREAD

**Issue by sadeemkhalaf** [regulaforensics/react-native-face-api#6]
AutoLinking is not working for IOS pods
I created a patch with this change and it worked 

**File name:** _RNFaceApi.podspec_

**File Content:**
`require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name         = "RNFaceApi"
  s.version      = package['version']
  s.summary      = package['description']
  s.license      = package['license']

  s.authors      = { 'RegulaForensics' => 'support@regulaforensics.com' }
  s.homepage     = 'https://regulaforensics.com'

  s.source       = { :http => 'file:' + __dir__ }

  s.ios.deployment_target = '9.0.0'
  s.dependency 'FaceSDK'

  s.dependency 'React'
end
`

**Comment by pkondrashkov** [comment]
Hello @sadeemkhalaf
Thanks for letting us know about the issue. 

This should be fixed once this [PR](https://github.com/regulaforensics/react-native-face-api/pull/7) is merged.

**Comment by sadeemkhalaf** [comment]
@pkondrashkov thank you for this super fast fix!
this is needed for react-native v64, it's working fine for previous versions, when I downgraded to v63 it worked !
